### PR TITLE
Prevent infinite recursion in number operation

### LINKED ISSUE #113: Wrong error message due to operation overloading
There is a slight unexpected behaviour in the operation overloading on numbers done [here](https://github.com/twitter/torch-autograd/blob/master/src/support.lua#L65-L87) 

If we try to add (same with mul and sub) something that does not have an `__add` in its metatable to a number, we get to an infinite recursion leading to a stack overflow.
Below is an example using nil.
```lua
local function add(a,b)
    return a + b
end

local ok, res = pcall(add, nil, 2)
print(res)
-- a.lua:2: attempt to perform arithmetic on local 'a' (a nil value)

require 'autograd'

local ok, res = pcall(add, nil, 2)
print(res)
-- ...e/alban/torch/install/share/lua/5.1/autograd/support.lua:67: stack overflow
```

This could be solve by checking whether or not the first element has the proper function in its metatable before calling `a+b` [here](https://github.com/twitter/torch-autograd/blob/master/src/support.lua#L70). Do you guys think there would be a better way to solve this? I can prepare a PR if you agree with the proposed fix.

### PR DESCRIPTION
**Pull request by albanD**
Fix #113 
So after looking more closely, the only way to be in this state ([l70](https://github.com/twitter/torch-autograd/blob/14e7f9bd79b1905295a7075e894cf850e3599357/src/support.lua#L70), [l77](https://github.com/twitter/torch-autograd/blob/14e7f9bd79b1905295a7075e894cf850e3599357/src/support.lua#L77) and [l84](https://github.com/twitter/torch-autograd/blob/14e7f9bd79b1905295a7075e894cf850e3599357/src/support.lua#L84)) is if `a` is not a number,  `b` is and `a` does not have an `__add` method. Since the original number addition can only work with numbers, we should always raise an error when getting to this state.

For clarity I changed the position in the stack of the error (as is done in the original number operation). The new error message is:
```lua
local function add(a,b)
    return a + b
end

local ok, res = pcall(add, nil, 2)
print(res)
-- foo.lua:2: attempt to perform arithmetic on local 'a' (a nil value) 

require 'autograd'

local ok, res = pcall(add, nil, 2)
print(res)
-- foo.lua:2: attempt to perform arithmetic on a nil value	
```

### CODE REVIEW

File: src/support.lua [hunk 1]
```diff
@@ -67,21 +67,24 @@ local numberMetatable = {
...
+         error("attempt to perform a substraction between a number and a " ..
+            type(a) .. ".", 2)
       end
    end,
    __mul = function(a,b)
       if type(a) == "number"  then
          return b * a
       else
-         return a * b
+         error("attempt to perform an multiplication between a number and a " ..
```
Comment (luketwitter) [inline src/support.lua]: "a multiplication"

File: src/support.lua [hunk 2]
```diff
@@ -67,21 +67,24 @@ local numberMetatable = {
...
+         error("attempt to perform an addition between a number and a " ..
+            type(a) .. ".", 2)
       end
    end,
    __sub = function(a,b)
       if type(a) == "number"  then
          return -b + a
       else
-         return a - b
+         error("attempt to perform a substraction between a number and a " ..
```
Comment (luketwitter) [inline src/support.lua]: "subtraction"

**Comment by luketwitter** [comment]
Thanks for the fix. Could you make the messages match lua's errors for this? e.g. "attempt to perform arithmetic on a nil value"?

**Comment by albanD** [comment]
@luketwitter fixed. The only difference is that it won't recover the variable name from the context above.
Let me know if you want me to rebase/squash the commits.

**Comment by luketwitter** [comment]
Thanks!
